# nanovisor - A Minimal Type 2 Hypervisor
#
# Copyright (c) 2026 Mohammad Shehar Yaar Tausif <sheharyaar48@gmail.com>
#
# This file is licensed under the MIT License.
# Generated by ChatGPT 5.2

CC = gcc
CFLAGS = -Wall -Wextra -O2

# Enable debug flags if DEBUG=1
ifeq ($(DEBUG),1)
	CFLAGS += -DDEBUG=1 -g
endif

TARGET = svm
BUILD_DIR = build
SRC = svm.c
BIN = $(BUILD_DIR)/$(TARGET)

all: $(BIN)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BIN): $(SRC) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -o $(BIN) $(SRC)

clean:
	rm -rf $(BUILD_DIR)
