# nanovisor - A Minimal Type 2 Hypervisor
# Copyright (c) 2026 Mohammad Shehar Yaar Tausif <sheharyaar48@gmail.com>
# Generated by ChatGPT 5.2

obj-m += nanovisor.o
ccflags-y := -g -DDEBUG

# Path to the kernel build directory
KDIR := /lib/modules/$(shell uname -r)/build

# Current directory
PWD := $(shell pwd)

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

